"""
Archivo para guardar cadenas
"""

class Cadena:
    main = "main"
    inicio = "inicio"
    elegir_unimones = "elegir_unimones"
    elegir_habilidades = "elegir_habilidades"
    estadisticas = "estadisticas"
    configuracion = "configuracion"
    combate = "combate"
    atacar = "atacar"
    sacar = "sacar"
    equipo = "equipo"
    usuario = "usuario"
    NPC = "NPC"
    a = "a"
    b = "b"
    atras_4 = "atras_4"
    atras_5 = "atras_5"
    Físico = "Físico"
    Especial = "Especial"
    Estado = "estado"
    efectivo = "efectivo"
    muy_efectivo = "muy_efectivo"
    poco_efectivo = "poco_efectivo"
    Nada = "Nada"
    Dormido = "Dormido"
    Congelado = "Congelado"
    Paralizado = "Paralizado"
    Quemado = "Quemado"
    Envenenado = "Envenenado"
    GravementeEnvenenado = "GravementeEnvenenado"
    unimon_usr = "unimon_usr"
    unimon_npc = "unimon_npc"
    Empate = "Empate"
    Perdiste = "Perdiste"
    Ganaste = "Ganaste"